### ISSUE TITLE
port conflict 

### ISSUE THREAD

**Issue by Shihara-Dilshan** [Shihara-Dilshan/Fast.lk#3]
port conflict buyer and order both uses 5003

**Comment by pramitha1166** [comment]
So is there a need for PORT change?

**Comment by Shihara-Dilshan** [comment]
==========================
EmailService : PORT 5001
==========================
ProductService : PORT 5002
==========================
OrderService : PORT 5003
==========================
SellerService : PORT 5004
==========================
